# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/herbert/Desktop/code/CartPole_with_RL/window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 1000)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-image: url(:/resources/background.png);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_author = QtWidgets.QLabel(self.centralwidget)
        self.label_author.setMaximumSize(QtCore.QSize(500, 100))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.label_author.setFont(font)
        self.label_author.setAutoFillBackground(False)
        self.label_author.setStyleSheet("QFrame{\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 rgba(245, 194, 17,200), stop:1 rgba(224, 121, 16,200));\n"
"    border-radius:25px;\n"
"    border:none\n"
"}")
        self.label_author.setAlignment(QtCore.Qt.AlignCenter)
        self.label_author.setObjectName("label_author")
        self.gridLayout.addWidget(self.label_author, 1, 1, 1, 1)
        self.frame_theme = QtWidgets.QFrame(self.centralwidget)
        self.frame_theme.setMaximumSize(QtCore.QSize(16777215, 600))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frame_theme.setFont(font)
        self.frame_theme.setStyleSheet("QFrame{\n"
"    border:none\n"
"}")
        self.frame_theme.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_theme.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_theme.setObjectName("frame_theme")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_theme)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_title = QtWidgets.QLabel(self.frame_theme)
        self.label_title.setMaximumSize(QtCore.QSize(1000, 200))
        font = QtGui.QFont()
        font.setPointSize(58)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("QFrame{\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 rgba(153, 193, 241,200), stop:1 rgba(237, 51, 59,200));\n"
"    border-radius:25px;\n"
"}")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout.addWidget(self.label_title)
        self.gridLayout.addWidget(self.frame_theme, 0, 1, 1, 1)
        self.pushButton_man = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_man.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.pushButton_man.setFont(font)
        self.pushButton_man.setMouseTracking(True)
        self.pushButton_man.setStyleSheet("QPushButton{\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 0, 0, 200), stop:1 rgba(0, 255, 0, 200));\n"
"    border:none;\n"
"    height:100px;\n"
"    border-radius:25px;\n"
"}\n"
"QPushButton:hover {\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 rgba(141, 228, 226,210), stop:1 rgba(0, 255, 0, 210));\n"
"}")
        self.pushButton_man.setIconSize(QtCore.QSize(50, 16))
        self.pushButton_man.setObjectName("pushButton_man")
        self.gridLayout.addWidget(self.pushButton_man, 2, 2, 1, 1)
        self.pushButton_auto = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_auto.setEnabled(True)
        self.pushButton_auto.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.pushButton_auto.setFont(font)
        self.pushButton_auto.setMouseTracking(True)
        self.pushButton_auto.setStyleSheet("QPushButton{\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 0, 0, 200), stop:1 rgba(0, 255, 0, 200));\n"
"    border:none;\n"
"    height:100px;\n"
"    border-radius:25px;\n"
"}\n"
"QPushButton:hover {\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 rgba(141, 228, 226,210), stop:1 rgba(0, 255, 0, 210));\n"
"}")
        self.pushButton_auto.setIconSize(QtCore.QSize(50, 16))
        self.pushButton_auto.setObjectName("pushButton_auto")
        self.gridLayout.addWidget(self.pushButton_auto, 2, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("QFrame{\n"
"    border:none\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_music = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_music.setGeometry(QtCore.QRect(440, 10, 50, 50))
        self.pushButton_music.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_music.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/music_off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/resources/music.gif"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/resources/music_off.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/resources/music.gif"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/resources/music_off.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/resources/music.gif"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButton_music.setIcon(icon)
        self.pushButton_music.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_music.setObjectName("pushButton_music")
        self.gridLayout.addWidget(self.frame_2, 0, 2, 1, 1)
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_back.setMaximumSize(QtCore.QSize(100, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_back.setStyleSheet("QPushButton{\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 0, 0, 200), stop:1 rgba(0, 255, 0, 200));\n"
"    border:none;\n"
"    height:50px;\n"
"    border-radius:25px;\n"
"}\n"
"QPushButton:hover {\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 rgba(141, 228, 226,210), stop:1 rgba(0, 255, 0, 210));\n"
"}")
        self.pushButton_back.setObjectName("pushButton_back")
        self.gridLayout.addWidget(self.pushButton_back, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_author.setText(_translate("MainWindow", "Made by Skyper"))
        self.label_title.setText(_translate("MainWindow", "CarPole Game"))
        self.pushButton_man.setText(_translate("MainWindow", "手动挡"))
        self.pushButton_auto.setText(_translate("MainWindow", "自动挡"))
        self.pushButton_back.setText(_translate("MainWindow", "退出"))
import background_rc
